### ISSUE TITLE
Albums and Tracks with question mark and slash

### ISSUE THREAD

**Issue by lazside** [RemixDev/DRemixIssues#136]
Hello, Albums and tracks with question mark and slash is downloading with underscore. can this be fixed with empty space instead of a underscore

**example**

![track](https://user-images.githubusercontent.com/57320926/71765436-068d2500-2ef5-11ea-976f-385dd241ae4b.png)

![album](https://user-images.githubusercontent.com/57320926/71765438-0a20ac00-2ef5-11ea-8451-78969cae32c3.png)

![Naamloos](https://user-images.githubusercontent.com/57320926/71765439-0d1b9c80-2ef5-11ea-8406-15f3c1ed6dbc.png)

**Comment by RemixDev** [comment]
Why should it be an empty space insead of an underscore?

**Comment by lazside** [comment]
I saw SMLoadr doing empty space on tracks and - Dash on  folder names thought it would be a nice addition


looks a bit ugly behind the file/folder names

![616](https://user-images.githubusercontent.com/57320926/72070099-01f7b080-32e9-11ea-85fa-4a1f3b15f23d.png)

**Comment by RemixDev** [comment]
Added with commit [`4b6cee9c8d`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/4b6cee9c8d91083ca87bd8e7c1351690eb5eda10)

**Comment by lazside** [comment]
Thank you for your work.

Sorry maybe I wasn't clear becouse my english
issue now is with slashes on tracks and question mark on folders

**example tracks with slashes doing 2 spaces**
can this be replaced with only 1 space
![trackt with slash double space](https://user-images.githubusercontent.com/57320926/72348889-ad36aa00-36db-11ea-9f58-10ddab2eccb7.png)



**example folder with question mark on the end**
can this be blank (nothing on the end)
![Naamloos23132](https://user-images.githubusercontent.com/57320926/72348938-cb9ca580-36db-11ea-9ad1-3ef0a40595b2.png)

**Comment by RemixDev** [comment]
I can only replace the char, I can't remove them

Should I replace everything with a space or a blank?

**Comment by lazside** [comment]
Blank should be fine.
Thanks

**Comment by RemixDev** [comment]
Added with [`4a389d3aa2`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/4a389d3aa2614f622a54de2378839ec93a8f8db3)

**Comment by jungletek** [comment]
For what it's worth, I *really* don't like this change.

IMO, the old behavior of replacing illegal characters with an underscore is more graceful, because you have a better indicator that an illegal character was replaced.

For example, a hypothetical release titled like this on Deezer: ArtistName - TrackName1 / TrackName 2

When the forward-slash gets changed to an underscore, I can easily see it's been replaced compared to 2 spaces with a NULL character in the middle (so just 2 spaces, really).

With the former, you can script something like "replace underscore with hyphen" much easier than "find 2 spaces and insert a hyphen".

If you won't revert it, would you consider an option to pick which behavior of the 2 we prefer (if it's not too much work to have both and the choice to select)? The way I imagine it, you could have (yet another, lol) option in the settings to choose what you want to replace illegal chars with.

Too much to ask, or a reasonable compromise?

**Comment by 1024mb** [comment]
This should have been an option instead of default behavior, I too agree with jungletek, that's even the standard isn't it?

**Comment by lazside** [comment]
Sorry guys and sorry Dev for the trouble.
My intention was not 2 spaces, the intention was to get rid of underscore at the end of the folders and tracks. 

Jungletek's idea is much better

**Comment by RemixDev** [comment]
Added again with latest commit
Please let it be the last one
